version: "3.9"

services:
  widget-static:
    build:
      context: .
      dockerfile: dockerfile.static
    ports:
      - "8080:80"

  widget-ssr:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
