services:
  widget-static:
    build:
      context: .
      dockerfile: DockerFile.static
    ports:
      - "8080:8080"

  widget-ssr:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
